# Generated by Django 3.2.6 on 2021-08-29 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_separator', models.CharField(choices=[('Comma (,)', 'Comma (,)'), ('Dot (.)', 'Dot (.)')], max_length=25)),
                ('string_character', models.CharField(choices=[('Double-quote (")', 'Double-quote (")'), ("Single-quote (')", "Single-quote (')")], max_length=25)),
                ('name', models.CharField(max_length=124)),
                ('modified', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
