# Generated by Django 3.2.6 on 2021-08-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0002_auto_20210829_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='data_generator.schema'),
        ),
        migrations.AlterField(
            model_name='column',
            name='typeof',
            field=models.CharField(choices=[('name', 'Full name'), ('company', 'Company name'), ('job', 'Job'), ('integer', 'Integer'), ('phone_number', 'Phone number'), ('address', 'Address'), ('email', 'Email'), ('domain_name', 'Domain name')], max_length=48),
        ),
    ]
