# Generated by Django 3.2.6 on 2021-08-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0003_auto_20210830_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_row', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready')], default='Processing', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('csv_file', models.FileField(null=True, upload_to='data_sets/')),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='data_generator.schema')),
            ],
        ),
    ]
